-- JUNIOR JOI TEAM LIST - COMPLETE DATABASE SETUP / UPDATE
-- Run this in the EXISTING Supabase project.

create extension if not exists pgcrypto;

create table if not exists public.joi_team_submissions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  team_name text not null,
  age_group text not null,
  division text,
  light_kit_colour text not null,
  dark_kit_colour text not null,
  province text,
  head_coach_name text not null,
  assistant_coach_name text,
  coach_contact text not null,
  school_head_name text not null,
  school_mic_name text not null,
  coach_signature text,
  school_head_signature text,
  school_mic_signature text,
  coach_signature_date date,
  school_head_signature_date date,
  school_mic_signature_date date,
  stamp_path text,
  status text not null default 'submitted'
);

alter table public.joi_team_submissions add column if not exists division text;

do $$
declare c record;
begin
  for c in
    select conname from pg_constraint
    where conrelid='public.joi_team_submissions'::regclass and contype='c'
      and pg_get_constraintdef(oid) ilike '%age_group%'
  loop execute format('alter table public.joi_team_submissions drop constraint if exists %I',c.conname);
  end loop;
end $$;

alter table public.joi_team_submissions
add constraint joi_team_submissions_age_group_check
check (age_group in ('U13','U14','U15','U16','U19'));

create table if not exists public.joi_team_players (
  id bigint generated by default as identity primary key,
  submission_id uuid not null references public.joi_team_submissions(id) on delete cascade,
  player_no integer not null check(player_no between 1 and 12),
  first_name text not null,
  surname text not null,
  date_of_birth text not null,
  light_kit_number text not null,
  dark_kit_number text not null,
  unique(submission_id,player_no)
);

alter table public.joi_team_submissions enable row level security;
alter table public.joi_team_players enable row level security;

-- Public coaches can SEND only.
drop policy if exists "public can submit joi teams" on public.joi_team_submissions;
create policy "public can submit joi teams" on public.joi_team_submissions
for insert to anon with check(true);

drop policy if exists "public can submit joi players" on public.joi_team_players;
create policy "public can submit joi players" on public.joi_team_players
for insert to anon with check(true);

-- Signed-in organisers can read everything in the admin dashboard.
drop policy if exists "authenticated organisers can read joi teams" on public.joi_team_submissions;
create policy "authenticated organisers can read joi teams" on public.joi_team_submissions
for select to authenticated using(true);

drop policy if exists "authenticated organisers can read joi players" on public.joi_team_players;
create policy "authenticated organisers can read joi players" on public.joi_team_players
for select to authenticated using(true);

insert into storage.buckets(id,name,public)
values('joi-team-stamps','joi-team-stamps',false)
on conflict(id) do nothing;

drop policy if exists "public can upload joi team stamps" on storage.objects;
create policy "public can upload joi team stamps" on storage.objects
for insert to anon with check(bucket_id='joi-team-stamps');

drop policy if exists "public can update joi team stamps" on storage.objects;
create policy "public can update joi team stamps" on storage.objects
for update to anon using(bucket_id='joi-team-stamps') with check(bucket_id='joi-team-stamps');

drop policy if exists "authenticated organisers can view joi stamps" on storage.objects;
create policy "authenticated organisers can view joi stamps" on storage.objects
for select to authenticated using(bucket_id='joi-team-stamps');
